export const campaignStringData = [
  {
    campaignStringName: 'NN media',
    created: 'saba',
    duration: 36,
    loops: 6,
    state: 'Submitted',
    action: 'true',
    campaignData: [
      {
        campaignName: 'MX Player',
        duration: 12,
        loops: 2,
        state: 'Submitted',
        action: 'true',
      },
      {
        campaignName: 'Neuro Android',
        duration: 12,
        loops: 2,
        state: 'Submitted',
        action: 'true',
      },
      {
        campaignName: 'Pan Neuro',
        duration: 12,
        loops: 2,
        state: 'Submitted',
        action: 'true',
      },
    ],
  },
  {
    campaignStringName: 'Neuro Group',
    created: 'saba',
    duration: 24,
    loops: 4,
    state: 'Published',
    action: 'true',
    campaignData: [
      {
        campaignName: 'MX Player',
        duration: 12,
        loops: 2,
        state: 'Published',
        action: 'true',
      },
      {
        campaignName: 'Pan Neuro',
        duration: 12,
        loops: 2,
        state: 'Published',
        action: 'true',
      },
    ],
  },
  {
    campaignStringName: 'Android Group',
    created: 'saba',
    duration: 24,
    loops: 4,
    state: 'Submitted',
    action: 'true',
    campaignData: [
      {
        campaignName: 'MX Player',
        duration: 12,
        loops: 2,
        state: 'Submitted',
        action: 'true',
      },
      {
        campaignName: 'Pan Neuro',
        duration: 12,
        loops: 2,
        state: 'Submitted',
        action: 'true',
      },
    ],
  },
  {
    campaignStringName: 'Dummy Group',
    created: 'saba',
    duration: 24,
    loops: 4,
    state: 'Draft',
    action: 'true',
    campaignData: [
      {
        campaignName: 'MX Player',
        duration: 12,
        loops: 2,
        state: 'Draft',
        action: 'true',
      },
      {
        campaignName: 'Pan Neuro',
        duration: 12,
        loops: 2,
        state: 'Draft',
        action: 'true',
      },
    ],
  },
  {
    campaignStringName: 'Dummy Group 2',
    created: 'saba',
    duration: 24,
    loops: 4,
    state: 'Submitted',
    action: 'true',
    campaignData: [
      {
        campaignName: 'MX Player',
        duration: 12,
        loops: 2,
        state: 'Submitted',
        action: 'true',
      },
      {
        campaignName: 'Pan Neuro',
        duration: 12,
        loops: 2,
        state: 'Submitted',
        action: 'true',
      },
    ],
  },
  {
    campaignStringName: 'Dummy Group 1',
    created: 'saba',
    duration: 24,
    loops: 4,
    state: 'Submitted',
    action: 'true',
    campaignData: [
      {
        campaignName: 'MX Player',
        duration: 12,
        loops: 2,
        state: 'Submitted',
        action: 'true',
      },
      {
        campaignName: 'Pan Neuro',
        duration: 12,
        loops: 2,
        state: 'Submitted',
        action: 'true',
      },
    ],
  },
];
