export const PREVILAGES = {
    LOCATION: {
      VIEW_LOCATION: "VIEW_LOCATION",
      ADD_LOCATION: "ADD_LOCATION",
      EDIT_LOCATION: "EDIT_LOCATION",
      DELETE_LOCATION: "DELETE_LOCATION",
    },
    TPA: {
      VIEW_TPA: "VIEW_TPA",
      ADD_TPA: "ADD_TPA",
      EDIT_TPA: "EDIT_TPA",
      DELETE_TPA: "DELETE_TPA",
    },
    DEVICE_SETTING: {
      EDIT_DEVICE_SETTING: "EDIT_DEVICE_SETTING",
      VIEW_DEVICE_SETTING: "VIEW_DEVICE_SETTING",
    },
    DOWNLOAD: {
      VIEW_DOWNLOAD: "VIEW_DOWNLOAD",
    },
    ROLE: {
      VIEW_ROLE: "VIEW_ROLE",
      ADD_ROLE: "ADD_ROLE",
      EDIT_ROLE: "EDIT_ROLE",
      DELETE_ROLE: "DELETE_ROLE",
    },
    CUSTOMER_SETUP: {
      ADD_CUSTOMER_SETUP: "ADD_CUSTOMER_SETUP",
      VIEW_CUSTOMER_SETUP: "VIEW_CUSTOMER_SETUP",
    },
    TPA_REPORTS: {
      VIEW_TPA_REPORTS: "VIEW_TPA_REPORTS",
      ADD_TPA_REPORTS: "ADD_TPA_REPORTS",
      EDIT_TPA_REPORTS: "EDIT_TPA_REPORTS",
      DELETE_TPA_REPORTS: "DELETE_TPA_REPORTS",
    },
    CUSTOMER_DEVICE_CONFIG: {
      ADD_CUSTOMER_DEVICE_CONFIG: "ADD_CUSTOMER_DEVICE_CONFIG",
      EDIT_CUSTOMER_DEVICE_CONFIG: "EDIT_CUSTOMER_DEVICE_CONFIG",
      VIEW_CUSTOMER_DEVICE_CONFIG: "VIEW_CUSTOMER_DEVICE_CONFIG",
      DELETE_CUSTOMER_DEVICE_CONFIG: "DELETE_CUSTOMER_DEVICE_CONFIG",
    },
    FA_REPORTS: {
      VIEW_FA_REPORTS: "VIEW_FA_REPORTS",
    },
    REPORTS: {
      VIEW_REPORTS: "VIEW_REPORTS",
    },
    PLANOGRAM: {
      VIEW_PLANOGRAM: "VIEW_PLANOGRAM",
      ADD_PLANOGRAM: "ADD_PLANOGRAM",
      EDIT_PLANOGRAM: "EDIT_PLANOGRAM",
      DELETE_PLANOGRAM: "DELETE_PLANOGRAM",
      APPROVE_PLANOGRAM: "APPROVE_PLANOGRAM",
    },
    DEVICE_ONBOARD: {
      VIEW_DEVICE_ONBOARD: "VIEW_DEVICE_ONBOARD",
      ADD_DEVICE_ONBOARD: "ADD_DEVICE_ONBOARD",
    },
    SCHEDULER: {
      VIEW_SCHEDULER: "VIEW_SCHEDULER",
      ADD_SCHEDULER: "ADD_SCHEDULER",
      EDIT_SCHEDULER: "EDIT_SCHEDULER",
      DELETE_SCHEDULER: "DELETE_SCHEDULER",
      APPROVE_SCHEDULER: "APPROVE_SCHEDULER",
    },
    CUSTOMER: {
      VIEW_CUSTOMER: "VIEW_CUSTOMER",
      EDIT_CUSTOMER: "EDIT_CUSTOMER",
      DELETE_CUSTOMER: "DELETE_CUSTOMER",
    },
    MEDIA: {
      VIEW_MEDIA: "VIEW_MEDIA",
      ADD_MEDIA: "ADD_MEDIA",
      EDIT_MEDIA: "EDIT_MEDIA",
      DELETE_MEDIA: "DELETE_MEDIA",
    },
    TEMPLATE: {
      VIEW_TEMPLATE: "VIEW_TEMPLATE",
      ADD_TEMPLATE: "ADD_TEMPLATE",
      EDIT_TEMPLATE: "EDIT_TEMPLATE",
      DELETE_TEMPLATE: "DELETE_TEMPLATE",
    },
    CONTENT: {
      VIEW_CONTENT: "VIEW_CONTENT",
      ADD_CONTENT: "ADD_CONTENT",
      EDIT_CONTENT: "EDIT_CONTENT",
      DELETE_CONTENT: "DELETE_CONTENT",
    },
    ASPECT_RATIO: {
      ADD_ASPECT_RATIO: "ADD_ASPECT_RATIO",
      EDIT_ASPECT_RATIO: "EDIT_ASPECT_RATIO",
      VIEW_ASPECT_RATIO: "VIEW_ASPECT_RATIO",
      DELETE_ASPECT_RATIO: "DELETE_ASPECT_RATIO",
    },
    DEVICE_GROUP: {
      VIEW_DEVICE_GROUP: "VIEW_DEVICE_GROUP",
      ADD_DEVICE_GROUP: "ADD_DEVICE_GROUP",
      EDIT_DEVICE_GROUP: "EDIT_DEVICE_GROUP",
      DELETE_DEVICE_GROUP: "DELETE_DEVICE_GROUP",
    },
    CAMPAIGN: {
      VIEW_CAMPAIGN: "VIEW_CAMPAIGN",
      ADD_CAMPAIGN: "ADD_CAMPAIGN",
      EDIT_CAMPAIGN: "EDIT_CAMPAIGN",
      DELETE_CAMPAIGN: "DELETE_CAMPAIGN",
      APPROVE_CAMPAIGN: "APPROVE_CAMPAIGN",
    },
    MIDDLEWARE: {
      ACTIVE_MIDDLEWARE: "ACTIVE_MIDDLEWARE",
    },
    DEVICE: {
      VIEW_DEVICE: "VIEW_DEVICE",
      ADD_DEVICE: "ADD_DEVICE",
      EDIT_DEVICE: "EDIT_DEVICE",
      DELETE_DEVICE: "DELETE_DEVICE",
    },
    USER: {
      VIEW_USER: "VIEW_USER",
      ADD_USER: "ADD_USER",
      EDIT_USER: "EDIT_USER",
      DELETE_USER: "DELETE_USER",
    },
    CMS_ADVERTISEMENT: {
      ADD_CMS_ADVERTISEMENT: "ADD_CMS_ADVERTISEMENT",
      EDIT_CMS_ADVERTISEMENT: "EDIT_CMS_ADVERTISEMENT",
      VIEW_CMS_ADVERTISEMENT: "VIEW_CMS_ADVERTISEMENT",
      DELETE_CMS_ADVERTISEMENT: "DELETE_CMS_ADVERTISEMENT",
    },
    QMS: {
      ADD_QMS: "ADD_QMS",
      EDIT_QMS: "EDIT_QMS",
      VIEW_QMS: "VIEW_QMS",
    },
    FA_RULE_ENGINE: {
      ADD_FA_RULE_ENGINE: "ADD_FA_RULE_ENGINE",
      EDIT_FA_RULE_ENGINE: "EDIT_FA_RULE_ENGINE",
      VIEW_FA_RULE_ENGINE: "VIEW_FA_RULE_ENGINE",
      DELETE_FA_RULE_ENGINE: "DELETE_FA_RULE_ENGINE",
    },
    DEMOGRAPHY_CAMPAIGN_REPORTS: {
      VIEW_DEMOGRAPHY_CAMPAIGN_REPORTS: "VIEW_DEMOGRAPHY_CAMPAIGN_REPORTS",
    },
    CAMPAIGN_STRING: {
      VIEW_CAMPAIGN_STRING: "VIEW_CAMPAIGN_STRING",
      ADD_CAMPAIGN_STRING: "ADD_CAMPAIGN_STRING",
      EDIT_CAMPAIGN_STRING: "EDIT_CAMPAIGN_STRING",
      DELETE_CAMPAIGN_STRING: "DELETE_CAMPAIGN_STRING",
      APPROVE_CAMPAIGN_STRING: "APPROVE_CAMPAIGN_STRING",
    },
    ORGANIZATION_SETTING: {
      VIEW_ORGANIZATION_SETTING: "VIEW_ORGANIZATION_SETTING",
      ADD_ORGANIZATION_SETTING: "ADD_ORGANIZATION_SETTING",
      EDIT_ORGANIZATION_SETTING: "EDIT_ORGANIZATION_SETTING",
      DELETE_ORGANIZATION_SETTING: "DELETE_ORGANIZATION_SETTING",
    },
  };
  