export const UPDATE_USER = "UPDATE_USER";
export const ENABLE_LOADER = "ENABLE_LOADER";
export const DISABLE_LOADER = "DISABLE_LOADER";

export const GET_RESOLUTION_DATA = "GET_RESOLUTION_DATA";
export const REMOVE_RESOLUTION_DATA = "REMOVE_RESOLUTION_DATA";

export const GET_TEMPLATE_DATA = "GET_RESOLUTION_DATA";
export const GET_TEMPLATE_DATA_PAGINATION = "GET_TEMPLATE_DATA_PAGINATION";
export const REMOVE_TEMPLATE_DATA = "REMOVE_RESOLUTION_DATA";

export const GET_MEDIALIB_DATA = "GET_MEDIALIB_DATA";
export const REMOVE_MEDIALIB_DATA = "REMOVE_MEDIALIB_DATA";
export const GET_MEDIA_ARCHIVED_DATA = "GET_MEDIA_ARCHIVED_DATA";

export const GET_CAMPAIGN_DATA = "GET_CAMPAIGN_DATA";
export const GET_CAMPAIGN_ARCHIVE_DATA = "GET_CAMPAIGN_ARCHIVE_DATA";
export const REMOVE_CAMPAIGN_DATA = "REMOVE_CAMPAIGN_DATA";

export const GET_CAMPAIGN_STRING_DATA = "GET_CAMPAIGN_STRING_DATA";
export const GET_CAMPAIGN_STRING_ARCHIVE_DATA =
  "GET_CAMPAIGN_STRING_ARCHIVE_DATA";
export const REMOVE_CAMPAIGN_STRING_DATA = "REMOVE_CAMPAIGN_STRING_DATA";

export const GET_PLONOGRAM_DATA = "GET_PLONOGRAM_DATA";
export const GET_PLONOGRAM_ARCHIVE_DATA = "GET_PLONOGRAM_ARCHIVE_DATA";
export const REMOVE_PLONOGRAM_DATA = "REMOVE_PLONOGRAM_DATA";

export const GET_LOCATION_LIST = "GET_LOCATION_LIST";
export const GET_DEVICE_GROUP = "GET_DEVICE_GROUP";
export const GET_DEVICE = "GET_DEVICE";

export const GET_USER_DATA = "GET_USER_DATA";
export const GET_ACTIVE_DATA = "GET_ACTIVE_DATA";

export const SET_RECENT_MEDIA_UPLOAD = "SET_RECENT_MEDIA_UPLOAD";
export const UPDATE_ACTIVE_SIDE_COUNT = "UPDATE_ACTIVE_SIDE_COUNT";

export const GET_SCHEDULAR_DATA = "GET_SCHEDULAR_DATA";
export const GET_SCHEDULAR_ARCHIVE_DATA = "GET_SCHEDULAR_ARCHIVE_DATA";
export const REMOVE_SCHEDULAR_DATA = "REMOVE_SCHEDULAR_DATA";

export const UPDATE_REGISTER_DEVICE_LIST = "UPDATE_REGISTER_DEVICE_LIST";
export const UPDATE_USER_WORK_FLOW = "UPDATE_USER_WORK_FLOW";

export const SET_USER_AUTHORIZATIONS = "SET_USER_AUTHORIZATIONS";
export const UPDATE_IS_APPROVER = "UPDATE_IS_APPROVER";

export const SET_IS_SCHEDULER_ENABLED = "SET_IS_SCHEDULER_ENABLED";
export const UPDATE_DRAWER_INDEX = "UPDATE_DRAWER_INDEX";
